name: Terraform Equivalence Tests

# This action will execute the suite of Terraform equivalence tests after a
# tag has been pushed for a new version.
#
# For now, it is just a skeleton action that will be populated shortly.

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "the Terraform version to equivalence test, eg. v1.3.1"
      run-id:
        required: true
        description: "the run identifier of a successful `Build Terraform CLI Packages` action that contains artifacts for the target version"

permissions:
  contents: read

jobs:
  skeleton-job:
    name: "Temporary job to be released with real work"
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello, world!"
